# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/awsctx
    binary: awsctx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/yetmike/awsctx/internal/awsctx.Version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - src: shell/awsctx.sh
        dst: bash_autocomplete
      - src: shell/awsctx.sh
        dst: zsh_autocomplete

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - name: awsctx
    repository:
      owner: yetmike
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/yetmike/awsctx"
    description: "Fast AWS profile and region switcher"
    license: MIT
    completions:
      bash: bash_autocomplete
      zsh: zsh_autocomplete

# scoops:
#   - name: awsctx
#     repository:
#       owner: yetmike
#       name: scoop-bucket
#     homepage: "https://github.com/yetmike/awsctx"
#     description: "Fast AWS profile and region switcher"
#     license: MIT
